### PR TITLE
Added Option to add Options

### PR DESCRIPTION
**Pull request by KaiserRuben**
The User can now type and if no option fits, he is able to add what he typed as option.

This feature can be toggled by the "addOptionOption" (default: false).

This pull request contains two new variables, one new function and a few new lines of html.

### CODE REVIEW

**Comment by janosh** [comment]
Hi there! Isn't this the same as [`allowUserOptions`](https://github.com/janosh/svelte-multiselect#props)? Maybe this feature should get its own [demo page](https://svelte-multiselect.netlify.app/demos/persistent) to make it more discoverable?

**Comment by KaiserRuben** [comment]
Hi, sorry. You are right and I am blind. Didn't see that feature. Thanks!🤦

**Comment by KaiserRuben** [comment]
Maybe it is worth to combine our two implementations though.

If I toggle `allowUserOptions={true}` and try to remove the options again, i get the error "MultiSelect: option with label test not found".
Personally, I believe the button I included is also more user friendly. But I guess that comes down to personal preference.

**Comment by janosh** [comment]
@KaiserRuben Definitely open to changes. Could you share a screen shot or recording of the error and the button you're referring to so I can reproduce?

**Comment by janosh** [comment]
I actually prefer the current prop name [`allowUserOptions`](https://github.com/janosh/svelte-multiselect#props) over `addOptionOption`. Easier to understand what it's for imo.

**Comment by janosh** [comment]
I think I have a simple fix over in #69. Just need to add some tests.

**Comment by KaiserRuben** [comment]
[allowUserOptions](https://github.com/janosh/svelte-multiselect#props) is the better name, agreed.
Also, I had a look at your fix, seems to work!

I still think it might be great to also add the button, similar to what I did in this pull request:

```html
        {#if addOptionOption}
          {#if searchText}
            <li class="addOption" on:click={addOption}>{addOptionsMsg}</li>
          {/if}
        {:else}
          <span>{noOptionsMsg}</span>
        {/if}
```

If you don't consider this necessary, feel free to close this pull request.

Thanks for your work and your help :)

**Comment by janosh** [comment]
@KaiserRuben I agree, the `addOptionMsg` is a good addition, making it much clearer to users that they can create custom options. But we'll have to implement it a bit differently to handle cases like not exceeding `maxSelect`.

**Pull request closed without merging**
