### PR TITLE
Hide input when maxSelect is 1 and a selection has been made

### LINKED ISSUE #174: Can the input at the end be omitted when a selection has been made and maxSelect is 1?
In the project I'm working on we have a few places where only 1 selection is to be made (maxSelect is 1). After making the selection the input unnecessarily takes up space, which makes css work harder when trying to fit everything, so I´m proposing that it is omitted in that case. I'm creating a PR for this (yay, my first code contribution to an open source project ever!).

### PR DESCRIPTION
**Pull request by egdegauperaa**
Closes #174 

Adds code to not render input if maxSelect is 1 and the user has made a selection.

### CODE REVIEW

**Comment by janosh** [comment]
@egdegauperaa Thanks for reporting #174! I've actually had that issue with myself with longer than necessary MultiSelects due to the `<input>` element. So I agree there's room for improvement here. Disappearing it completely is not the optimal solution though as it breaks user expectations IMO. Here's a screenrecording to show what I mean:

https://user-images.githubusercontent.com/30958850/203598537-200aa6c5-f21d-424e-b700-e640c47effc8.mp4

As a user I'd always expect to be able to enter text to filter down the dropdown list. That's no longer possible with this PR unless I clear the selected option first. Maybe we can make the `<input>` absolute-positioned to avoid taking up space but still allow input.

**Comment by egdegauperaa** [comment]
@janosh Have you considered letting svelte-multiselect change into a normal select list/dropdown with filter functionality when only one selection can be made? That would simplify both UI and implementation

**Comment by janosh** [comment]
I hadn't considered that. Interesting idea but I'm not convinced it would really simplify the code. Sounds like you'd need a lot of new CSS to get a consistent look across single and multiselect. Getting all the CSS variables to attach correctly in both cases also sounds like a hassle. That said, if you want to make a MVP, I'm happy to be convinced otherwise.

**Comment by janosh** [comment]
Thanks for update! Good to know you found a workaround for now. I reopened your issue cause I think you're right it would be an usability improvement if the `<input>` never increases the component width. It's on my todo list.

**Pull request closed without merging**
