### PR TITLE
feat: update MultiSelect.svelte for Svelte5 compatibility

### LINKED ISSUE #281: Svelte 5 support?
## Repro

- Svelte 5 Repro broken: https://stackblitz.com/edit/github-y3fhqr?file=package.json
- Looks like the event attributes must be functions, not strings, i.e.
    - Not `ondrop="return false"`, but `ondrop={() => false}`

image

## Additional context

Are there any plans for Svelte 5 updates yet? I know its early, but yeah figured I'd ask :blush:

### PR DESCRIPTION
**Pull request by dedo1911**
Closes #281

## Summary of major changes

1. fixes Svelte 5 compatibility issues

## Todos

1. Change events to new Svelte 5 format

### CODE REVIEW

**Comment by janosh** [comment]
ideally, i'd prefer to update package deps and unit tests to Svelte 5 in one go. that requires an update to mdsvexamples and fixing how unit tests create component instances

```ts
const select = new MultiSelect({
  target: document.body,
  props: { options },
})
```

> Attempted to instantiate src/lib/MultiSelect.svelte with `new MultiSelect`, which is no longer valid in Svelte 5. If this component is not under your control, set the `compatibility.componentApi` compiler option to `4` to keep it working. See https://svelte-5-preview.vercel.app/docs/breaking-changes#components-are-no-longer-classes for more information

**Comment by janosh** [comment]
svelte 5 compatibility is time sensitive so merging as is since upstream blockers could take months to resolve or might even require a docs rework since `mdsvexamples` looks to be unmaintained

**Review by janosh — APPROVED** [review]
svelte 5 compatibility is time sensitive so merging as is since upstream blockers could take months to resolve or might even require a docs rework since `mdsvexamples` looks to be unmaintained

**Comment by dedo1911** [comment]
In fact my idea was not to update deps to Svelte 5 already, but just make it work for people who can't wait, solving the build issues. I'm already using it in production and works just fine.
That was the reason of the smallest fix possible. This PR was not yet intended to provide full support to Svelte 5 features.
We'll dig into what's needed for the rework in another pr.

**Comment by janosh** [comment]
that would be great, looking forward to that PR! 👍 

could you give [v11.0.0-rc.1](https://github.com/janosh/svelte-multiselect/releases/tag/v11.0.0-rc.1) a try and let me know how it goes?

**Comment by dedo1911** [comment]
> could you give [v11.0.0-rc.1](https://github.com/janosh/svelte-multiselect/releases/tag/v11.0.0-rc.1) a try and let me know how it goes?

Looks good to me!

**Pull request merged**
