### PR TITLE
Add local to the transition

### PR DESCRIPTION
**Pull request by devbieres**

### CODE REVIEW

**Comment by janosh** [comment]
Could you briefly explain what problem you were experiencing and how this solves it?

**Comment by devbieres** [comment]
Hi,

Sorry, I think I made a mistake while trying to add a change in my fork before create a pull request.

Origin : I notice that the transition in MultiSelect may interfer with transition in parent component.

I simply to try to add a local as it's mentionned in the documentation.

I did not close the request just in case ...

**Comment by devbieres** [comment]
> Could you briefly explain what problem you were experiencing and how this solves it?

Sorry ... I was adding a comment ... as I said ... I think I made a bad click ...

Sorry again.

**Comment by janosh** [comment]
No worries, thanks for the fix! 👍

**Pull request merged**
