### PR TITLE
fix: allow object options to share the same label

### LINKED ISSUE #216: `Error: Cannot have duplicate keys in a keyed each` when two labels are the same
Hi! Thanks for this multiselect, it works like a charm.

I found a small bug today: if two options have the same label, the component throws `Error: Cannot have duplicate keys in a keyed each` on runtime. Because I work with user-supplied data, it happens from time to time with default names.

I tracked the bug down to this line:

https://github.com/janosh/svelte-multiselect/blob/e1e800b19ef0e9c81a65d8d2614248b906e51eb5/src/lib/MultiSelect.svelte#L471

I'll open a PR soon with one of the many potential fixes.

### PR DESCRIPTION
**Pull request by GauBen**
Closes #216

Keys can be objects, though somewhat discouraged.

> The key can be any object, but strings and numbers are recommended since they allow identity to persist when the objects themselves change.

### CODE REVIEW

**Comment by janosh** [comment]
I thought keys have to be primitive types?

**Comment by janosh** [comment]
Ah, I was wrong. From the [Svelte docs](https://svelte.dev/tutorial/keyed-each-blocks):

> You can use any object as the key, as Svelte uses a Map internally — in other words you could do (thing) instead of (thing.id). Using a string or number is generally safer, however, since it means identity persists without referential equality, for example when updating with fresh data from an API server.

**Comment by janosh** [comment]
Maybe we should still default to the option label as key but allow overriding this behavior by exposing a new prop `get_key: (option: Option) => unknown = get_label`?

**Comment by GauBen** [comment]
That's a an option too, but having two different values with the same name would still break svelte-multiselect

**Comment by janosh** [comment]
That's true but that was by design (until now anyway). Maybe it's not a good default. I think I made that decision at the time because I couldn't think of a strong use case for duplicate options. That was before allowing user-created options. But even now, maybe it's better to show a warning to users rather than allowing them to make duplicate options?

**Comment by GauBen** [comment]
That's right, shall I update this PR with a new `get_key` option? Or are you ok with `option` being used as an index?

The only thing that might break with the current PR is `animate:flip` when `selected` is updated by copy and not reference

https://svelte.dev/repl/60e7b5893b304b8f9e0ea094fe6bb293?version=3.57.0

**Comment by janosh** [comment]
> The only thing that might break with the current PR is animate:flip when selected is updated by copy and not reference

I didn't realize the downside was this small. Nice REPL btw. Very educational.

> That's right, shall I update this PR with a new get_key option?

No, I'm sold. I think we should just add a test that covers selecting two identical object options.

**Comment by GauBen** [comment]
Thanks for the quick merge!

**Pull request merged**
